# FLAGS = -std=c++14 -Wextra -Wall -Werror -Wno-sign-compare -Wno-unused-result -pedantic

all:
	g++ -std=c++14 -Ofast -pedantic -Wall -Werror -Wno-sign-compare main.cpp -o solution

# all: main.o
# 	g++ $(FLAGS) main.o -o solution

# main: main.cpp Additional.hpp Node.hpp Trie.hpp
# 	g++ $(FLAGS) -c main.cpp

clean:
	rm -rf *.o
